openapi: 3.0.1
info:
  description: "Aceasta este documentatia pentru API-ul de Lista Mesaje Factura Electronica"
  version: "1.0.0"
  title: "Lista Mesaje Factura Electronica"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8000"

tags:
- name: "Lista Mesaje Factura Electronica"
  description: "test"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "test"
  description: "test"

schemes:
- "https"
- "http"
paths:
  /FCTEL/rest/listaMesajeFactura:
    
    get:
      tags:
      - "Lista Mesaje Factura Electronica"
      summary: "Lista mesaje factura electronica"
      description: "Parametrii sunt folositi sub forma de query string in URL si niciunul nu este obligatoriu"
      operationId: "findPetsByStatus"
     
      parameters:
        - in: query
          name: zile
          schema:
            type: string
          required: false
          description: Nr. zile pe cat timp in urma se doreste interogarea
        - in: query
          name: cif
          schema:
            type: string
          required: false
          description: CIF/CNP
        - in: query
          name: serial
          schema:
            type: string
          required: false
          description: Serial
        - in: query
          name: token
          schema:
            type: string
          required: false
          description: Token
        
       
      responses:
        200:
          description: OK
          content:
            application/json:

          
              examples:
                structura json pentru lipsa mesaje:
                  summary: Nu exista mesaje
                  description: structura json pentru lipsa mesaje. exemplu parametrii zile=1 si cif=17788621
                  value: "{
                    'eroare': 'Nu exista mesaje in ultimele 1 zile',
                    'titlu': 'Lista Mesaje'
                      }"
                structura json pentru toate mesajele:
                  summary: Lista toate mesajele
                  description: structura json pentru toate mesajele
                  value: "{'mesaje':[{'data_creare':'202107061147','cif':'17788621','id_solicitare':'314507','detalii':'Nu exista informatii pentru duplicat pentru declaratia D300, pentru CUI 17788621 si perioada de raportare 6.2021','tip':'SOLICITARE','id':'9198055'},{'data_creare':'202107061147','cif':'17788621','id_solicitare':'314510','detalii':'Nu exista informatii pentru duplicat pentru declaratia D390, pentru CUI 17788621 si perioada de raportare 6.2019','tip':'SOLICITARE','id':'9198058'},{'data_creare':'202107061147','cif':'17788621','id_solicitare':'314511','detalii':'Nu exista informatii pentru duplicat pentru declaratia D390, pentru CUI 17788621 si perioada de raportare 6.2018','tip':'SOLICITARE','id':'9198059'}"
                structura json pentru eroare completare parametrii:
                  summary: Eroare completare parametrii
                  description: structura json pentru eroare completare parametrii
                  value: "{'eroare':'Numarul de zile introdus= a nu este un numar intreg','titlu':'Lista Mesaje'}"
                  
                  
                  
        500:
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
                example: Internal Server Error      
       
  
  /FCTEL/rest/test:
    get:
      tags:
      - "test"
      summary: "Test - Healthcheck"
      description: "Verifica daca api-ul functioneaza"
      operationId: "getPetById"
     
     
      responses:
        200:
          description: Test
          content:
            text/plain:
              schema:
                type: string
                example: test
                
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  ListaMesajeFacturaElectronica:
    type: "object"
    properties:
      zile:
        type: "string"
        format: "String"
      cif:
        type: "string"
        format: "String"
      serial:
        type: "string"
        format: "String"
      token:
        type: "string"
        format: "String"
      
      
   
  Test:
    type: "object"
   
      
 